from logging import Logger
from typing import Any

class classproperty:
    getter: Any = ...
    def __init__(self, getter: Any) -> None: ...
    def __get__(self, instance: Any, owner: Any): ...

def config_logging(log_level: int) -> None: ...
def get_logger(name: str) -> Logger: ...
