from typing import Any

class BusinessOrIndividualMixin:
    BUSINESS_IDENTIFIER: str = ...
    BUSINESS_TYPE: str = ...
    BUSINESS_URI: str = ...
    INDIVIDUAL_IDENTIFIER: str = ...
    INDIVIDUAL_TYPE: str = ...
    INDIVIDUAL_URI: str = ...
    def get_type(self) -> str: ...
    def get_type_uri(self) -> str: ...
    def set_identifier(self, taxpayer_id: Any, ein: Any) -> None: ...
