from ..exceptions import FieldError as FieldError, ValidationError as ValidationError
from .base import PaymentMethod as PaymentMethod, ZoopObject as ZoopObject
from typing import Any, Optional, List, Set

class BaseModeObject(ZoopObject):
    MODES: Set[str] = ...

    mode: str = ...
    percentage: Optional[str] = ...
    amount: Optional[str] = ...
    def init_custom_fields(self, mode: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def get_mode_required_fields_mapping(self) -> None: ...
    def get_validation_fields(self): ...
    @classmethod
    def get_required_fields(cls): ...
    @classmethod
    def get_percentage_required_fields(cls): ...
    @classmethod
    def get_fixed_required_fields(cls): ...

class Fine(BaseModeObject):
    FIXED: str = ...
    PERCENTAGE: str = ...
    MODES: Set[str] = ...

    start_date: Optional[str] = ...
    def get_mode_required_fields_mapping(self): ...
    @classmethod
    def get_non_required_fields(cls): ...

class Interest(BaseModeObject):
    DAILY_AMOUNT: str = ...
    DAILY_PERCENTAGE: str = ...
    MONTHLY_PERCENTAGE: str = ...
    MODES: Set[str] = ...

    start_date: Optional[str] = ...
    def get_mode_required_fields_mapping(self): ...
    @classmethod
    def get_non_required_fields(cls): ...

class Discount(BaseModeObject):
    FIXED: str = ...
    PERCENTAGE: str = ...
    MODES: Set[str] = ...

    limit_date: str = ...
    def get_mode_required_fields_mapping(self): ...
    @classmethod
    def get_required_fields(cls): ...

class BillingInstructions(ZoopObject):
    late_fee: Fine
    interest: Interest
    discount: List[Discount]
    def init_custom_fields(
        self,
        late_fee: Optional[Any] = ...,
        interest: Optional[Any] = ...,
        discount: Optional[Any] = ...,
        **kwargs: Any,
    ) -> None: ...
    @classmethod
    def get_required_fields(cls) -> set: ...

class Invoice(PaymentMethod):
    RESOURCE: str = ...

    expiration_date: str

    zoop_boleto_id: Optional[str]
    status: Optional[str]
    reference_number: Optional[str]
    document_number: Optional[str]
    recipient: Optional[str]
    bank_code: Optional[str]
    sequence: Optional[str]
    url: Optional[str]
    accepted: Optional[bool]
    printed: Optional[bool]
    downloaded: Optional[bool]
    fingerprint: Optional[str]
    paid_at: Optional[str]
    barcode: Optional[str]
    payment_limit_date: Optional[str]
    body_instructions: Optional[List[str]]
    billing_instructions: Optional[BillingInstructions]
    def init_custom_fields(self, billing_instructions: Optional[Any] = ..., **kwargs: Any) -> None: ...  # type: ignore
    @classmethod
    def get_required_fields(cls) -> set: ...
    @classmethod
    def get_non_required_fields(cls) -> set: ...
