name: pypi deploy

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install wheel and twine
      run: pip install wheel twine
    - name: build package
      run: python setup.py sdist bdist_wheel
    - name: deploy package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*